-- ZAKARIA MANSOUR Marketplace — Supabase PostgreSQL schema
-- Run once in Supabase SQL Editor.

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  password_hash text not null,
  role text not null default 'customer' check (role in ('owner','admin','moderator','support','finance','seller','customer')),
  status text not null default 'active' check (status in ('active','suspended','pending')),
  preferred_language text not null default 'ar' check (preferred_language in ('ar','en')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create unique index if not exists users_email_lower_unique on public.users (lower(email));

create table if not exists public.seller_applications (
  id bigint generated by default as identity primary key,
  user_id bigint not null unique references public.users(id) on delete cascade,
  store_name text not null,
  description text not null,
  status text not null default 'pending' check (status in ('pending','approved','rejected')),
  review_note text,
  reviewed_by bigint references public.users(id),
  created_at timestamptz not null default now(),
  reviewed_at timestamptz
);

create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  name_ar text not null,
  name_en text not null,
  type text not null check (type in ('digital','software','creative','service','course','physical')),
  is_active boolean not null default true
);

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  seller_id bigint not null references public.users(id),
  category_id bigint not null references public.categories(id),
  title_ar text not null,
  title_en text not null,
  description_ar text not null,
  description_en text not null,
  product_type text not null check (product_type in ('digital','software','creative','service','course','physical')),
  price_cents integer not null check (price_cents >= 0),
  currency varchar(3) not null default 'USD',
  status text not null default 'draft' check (status in ('draft','pending_review','published','rejected','archived')),
  review_note text,
  reviewed_by bigint references public.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.product_media (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  kind text not null default 'image' check (kind in ('image','preview')),
  storage_path text not null,
  mime_type text not null,
  alt_ar text,
  alt_en text,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.digital_files (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  storage_path text not null,
  original_name text not null,
  mime_type text not null,
  size_bytes bigint not null check (size_bytes >= 0),
  version text not null default '1.0',
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.carts (
  id bigint generated by default as identity primary key,
  user_id bigint not null unique references public.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table if not exists public.cart_items (
  cart_id bigint not null references public.carts(id) on delete cascade,
  product_id bigint not null references public.products(id) on delete cascade,
  quantity integer not null default 1 check (quantity > 0),
  primary key (cart_id, product_id)
);

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  order_number text not null unique,
  user_id bigint not null references public.users(id),
  status text not null default 'pending_payment' check (status in ('pending_payment','paid','processing','completed','cancelled','refunded')),
  currency varchar(3) not null,
  subtotal_cents integer not null check (subtotal_cents >= 0),
  discount_cents integer not null default 0 check (discount_cents >= 0),
  total_cents integer not null check (total_cents >= 0),
  payment_method text not null default 'pending' check (payment_method in ('pending','cash_on_delivery','bank_transfer')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  product_id bigint not null references public.products(id),
  seller_id bigint not null references public.users(id),
  title text not null,
  unit_price_cents integer not null check (unit_price_cents >= 0),
  quantity integer not null check (quantity > 0),
  product_type text not null
);

create table if not exists public.download_grants (
  id bigint generated by default as identity primary key,
  order_item_id bigint not null unique references public.order_items(id) on delete cascade,
  user_id bigint not null references public.users(id) on delete cascade,
  product_id bigint not null references public.products(id),
  max_downloads integer not null default 5 check (max_downloads > 0),
  download_count integer not null default 0 check (download_count >= 0),
  expires_at timestamptz,
  revoked_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.download_log (
  id bigint generated by default as identity primary key,
  grant_id bigint not null references public.download_grants(id) on delete cascade,
  file_id bigint not null references public.digital_files(id),
  ip_address text,
  user_agent text,
  downloaded_at timestamptz not null default now()
);

create table if not exists public.audit_log (
  id bigint generated by default as identity primary key,
  actor_id bigint references public.users(id),
  action text not null,
  entity_type text not null,
  entity_id bigint,
  metadata jsonb,
  created_at timestamptz not null default now()
);

create index if not exists products_status_idx on public.products(status);
create index if not exists products_seller_idx on public.products(seller_id);
create index if not exists product_media_product_idx on public.product_media(product_id);
create index if not exists digital_files_product_idx on public.digital_files(product_id);
create index if not exists orders_user_idx on public.orders(user_id);
create index if not exists orders_status_idx on public.orders(status);
create index if not exists download_grants_user_idx on public.download_grants(user_id);
create index if not exists download_log_grant_idx on public.download_log(grant_id);
create index if not exists audit_actor_idx on public.audit_log(actor_id);

insert into public.categories(slug,name_ar,name_en,type)
values
 ('digital-products','منتجات رقمية','Digital Products','digital'),
 ('software','برمجيات','Software','software'),
 ('creative','تصميم وإبداع','Creative','creative'),
 ('services','خدمات احترافية','Professional Services','service'),
 ('courses','كورسات','Courses','course'),
 ('physical','منتجات مختارة','Selected Products','physical')
on conflict (slug) do nothing;

-- Backend-only data: enable RLS and grant no browser policies.
alter table public.users enable row level security;
alter table public.seller_applications enable row level security;
alter table public.categories enable row level security;
alter table public.products enable row level security;
alter table public.product_media enable row level security;
alter table public.digital_files enable row level security;
alter table public.carts enable row level security;
alter table public.cart_items enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.download_grants enable row level security;
alter table public.download_log enable row level security;
alter table public.audit_log enable row level security;

-- Storage buckets: public optimized product images, private paid files.
insert into storage.buckets (id,name,public,file_size_limit,allowed_mime_types)
values ('product-images','product-images',true,8388608,array['image/jpeg','image/png','image/webp'])
on conflict (id) do update set public=excluded.public,file_size_limit=excluded.file_size_limit,allowed_mime_types=excluded.allowed_mime_types;

insert into storage.buckets (id,name,public,file_size_limit)
values ('digital-private','digital-private',false,209715200)
on conflict (id) do update set public=excluded.public,file_size_limit=excluded.file_size_limit;

select 'ZAKARIA MANSOUR marketplace schema created successfully' as result;
