import { Router } from 'express';
import { z } from 'zod';
import { throwIfError } from '../supabase-client.js';

export function createSupabaseAdminRouter(ctx){
 const router=Router();const{supabase,security,audit}=ctx;
 router.get('/seller/application',security.authenticate,async(req,res,next)=>{try{const r=await supabase.from('seller_applications').select('*').eq('user_id',Number(req.auth.sub)).maybeSingle();res.json({application:throwIfError(r)});}catch(e){next(e);}});
 router.post('/seller/applications',security.authenticate,async(req,res,next)=>{try{const p=z.object({storeName:z.string().trim().min(2).max(100),description:z.string().trim().min(20).max(1000)}).safeParse(req.body);if(!p.success)return res.status(400).json({error:'VALIDATION_ERROR'});const uid=Number(req.auth.sub);const user=throwIfError(await supabase.from('users').select('role').eq('id',uid).single());if(user.role!=='customer')return res.status(409).json({error:'NOT_ELIGIBLE'});const r=await supabase.from('seller_applications').insert({user_id:uid,store_name:p.data.storeName,description:p.data.description}).select().single();const app=throwIfError(r);await audit(uid,'seller.application.create','seller_application',app.id);res.status(201).json({id:app.id,status:app.status});}catch(e){next(e);}});
 router.get('/admin/overview',security.authenticate,security.allow('owner','admin','moderator','support','finance'),async(_req,res,next)=>{try{const count=async(table,filter)=>{let q=supabase.from(table).select('id',{count:'exact',head:true});if(filter)q=q.eq(filter[0],filter[1]);const r=await q;throwIfError(r);return r.count||0;};const [users,sellers,pendingSellers,publishedProducts,pendingProducts,orders]=await Promise.all([count('users'),count('users',['role','seller']),count('seller_applications',['status','pending']),count('products',['status','published']),count('products',['status','pending_review']),count('orders')]);res.json({overview:{users,sellers,pendingSellers,publishedProducts,pendingProducts,orders,revenueCents:0}});}catch(e){next(e);}});
 router.get('/admin/orders',security.authenticate,security.allow('owner','admin','support','finance'),async(_req,res,next)=>{try{const orders=throwIfError(await supabase.from('orders').select('*').order('created_at',{ascending:false}).limit(200));const ids=[...new Set(orders.map(o=>o.user_id))];const users=ids.length?throwIfError(await supabase.from('users').select('id,name,email').in('id',ids)):[];const map=Object.fromEntries(users.map(u=>[u.id,u]));res.json({orders:orders.map(o=>({...o,customer_name:map[o.user_id]?.name||'',customer_email:map[o.user_id]?.email||''}))});}catch(e){next(e);}});
 router.patch('/admin/orders/:id/status',security.authenticate,security.allow('owner','admin','finance'),async(req,res,next)=>{try{const status=z.enum(['pending_payment','paid','processing','completed','cancelled','refunded']).parse(req.body.status);const r=await supabase.rpc('update_marketplace_order_status',{p_order_id:Number(req.params.id),p_actor_id:Number(req.auth.sub),p_new_status:status});const order=throwIfError(r);res.json({order:Array.isArray(order)?order[0]:order});}catch(e){next(e);}});
 router.get('/admin/seller-applications',security.authenticate,security.allow('owner','admin','moderator'),async(_req,res,next)=>{try{const apps=throwIfError(await supabase.from('seller_applications').select('*').order('created_at',{ascending:false}));const ids=[...new Set(apps.map(a=>a.user_id))];const users=ids.length?throwIfError(await supabase.from('users').select('id,name,email').in('id',ids)):[];const map=Object.fromEntries(users.map(u=>[u.id,u]));res.json({applications:apps.map(a=>({...a,name:map[a.user_id]?.name,email:map[a.user_id]?.email}))});}catch(e){next(e);}});
 router.patch('/admin/seller-applications/:id',security.authenticate,security.allow('owner','admin'),async(req,res,next)=>{try{const p=z.object({decision:z.enum(['approved','rejected']),note:z.string().max(500).default('')}).parse(req.body);const app=throwIfError(await supabase.from('seller_applications').select('*').eq('id',Number(req.params.id)).eq('status','pending').maybeSingle());if(!app)return res.status(404).json({error:'APPLICATION_NOT_FOUND'});throwIfError(await supabase.from('seller_applications').update({status:p.decision,review_note:p.note,reviewed_by:Number(req.auth.sub),reviewed_at:new Date().toISOString()}).eq('id',app.id));if(p.decision==='approved')throwIfError(await supabase.from('users').update({role:'seller',updated_at:new Date().toISOString()}).eq('id',app.user_id));await audit(Number(req.auth.sub),`seller.application.${p.decision}`,'seller_application',app.id);res.json({id:app.id,status:p.decision});}catch(e){next(e);}});
 router.get('/admin/products/review',security.authenticate,security.allow('owner','admin','moderator'),async(_req,res,next)=>{try{const products=throwIfError(await supabase.from('products').select('*').eq('status','pending_review').order('created_at'));const ids=[...new Set(products.map(p=>p.seller_id))];const users=ids.length?throwIfError(await supabase.from('users').select('id,name').in('id',ids)):[];const sm=Object.fromEntries(users.map(u=>[u.id,u.name]));res.json({products:products.map(p=>({...p,seller_name:sm[p.seller_id]||'',category_name:''}))});}catch(e){next(e);}});
 router.patch('/admin/products/:id/review',security.authenticate,security.allow('owner','admin','moderator'),async(req,res,next)=>{try{const p=z.object({decision:z.enum(['published','rejected']),note:z.string().max(500).default('')}).parse(req.body);const product=throwIfError(await supabase.from('products').select('*').eq('id',Number(req.params.id)).eq('status','pending_review').maybeSingle());if(!product)return res.status(404).json({error:'PRODUCT_NOT_FOUND'});if(p.decision==='published'&&['digital','software','creative','course'].includes(product.product_type)){const f=await supabase.from('digital_files').select('id',{count:'exact',head:true}).eq('product_id',product.id).eq('is_active',true);if(!(f.count>0))return res.status(409).json({error:'DIGITAL_FILE_REQUIRED'});}throwIfError(await supabase.from('products').update({status:p.decision,review_note:p.note,reviewed_by:Number(req.auth.sub),updated_at:new Date().toISOString()}).eq('id',product.id));await audit(Number(req.auth.sub),`product.${p.decision}`,'product',product.id);res.json({id:product.id,status:p.decision});}catch(e){next(e);}});
 return router;
}
