import { Router } from 'express';
import multer from 'multer';
import sharp from 'sharp';
import { fileTypeFromBuffer } from 'file-type';
import { randomBytes } from 'node:crypto';
import { z } from 'zod';
import { throwIfError } from '../supabase-client.js';

const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:50*1024*1024,files:1}});
const digitalTypes=['digital','software','creative','course'];
const validate=(schema,body,res)=>{const p=schema.safeParse(body);if(!p.success){res.status(400).json({error:'VALIDATION_ERROR',message:'البيانات غير صحيحة.',fields:p.error.flatten().fieldErrors});return null;}return p.data;};

export function createSupabaseCatalogRouter(ctx,supabaseUrl){
 const router=Router();const {supabase,security,audit,userById}=ctx;
 const canManage=(user,product)=>user&&product&&(['owner','admin'].includes(user.role)||Number(product.seller_id)===Number(user.id));
 router.get('/categories',async(_req,res,next)=>{try{const r=await supabase.from('categories').select('*').eq('is_active',true).order('id');res.json({categories:throwIfError(r)});}catch(e){next(e);}});
 router.get('/products',async(req,res,next)=>{try{let q=supabase.from('products').select('id,product_type,price_cents,currency,title_ar,title_en,description_ar,description_en,created_at,category_id,seller_id').eq('status','published').order('created_at',{ascending:false}).limit(100);const r=await q;const products=throwIfError(r);const sellerIds=[...new Set(products.map(p=>p.seller_id))];const mediaIds=products.map(p=>p.id);const [sellersR,mediaR]=await Promise.all([supabase.from('users').select('id,name').in('id',sellerIds.length?sellerIds:[-1]),supabase.from('product_media').select('product_id,storage_path,sort_order').in('product_id',mediaIds.length?mediaIds:[-1]).eq('kind','image').order('sort_order')]);const sellers=Object.fromEntries(throwIfError(sellersR).map(x=>[x.id,x.name]));const media={};throwIfError(mediaR).forEach(x=>{if(!media[x.product_id])media[x.product_id]=x.storage_path;});const lang=req.query.lang==='en'?'en':'ar';let output=products.map(p=>({id:p.id,product_type:p.product_type,price_cents:p.price_cents,currency:p.currency,title:lang==='en'?p.title_en:p.title_ar,description:lang==='en'?p.description_en:p.description_ar,seller_name:sellers[p.seller_id]||'',image_url:media[p.id]?`${supabaseUrl}/storage/v1/object/public/product-images/${media[p.id]}`:null}));const term=String(req.query.q||'').trim().toLowerCase();if(term)output=output.filter(p=>`${p.title} ${p.description} ${p.seller_name}`.toLowerCase().includes(term));res.json({products:output});}catch(e){next(e);}});
 router.get('/products/:id',async(req,res,next)=>{try{const r=await supabase.from('products').select('*').eq('id',Number(req.params.id)).eq('status','published').maybeSingle();const p=throwIfError(r);if(!p)return res.status(404).json({error:'PRODUCT_NOT_FOUND'});const [sellerR,mediaR]=await Promise.all([supabase.from('users').select('id,name').eq('id',p.seller_id).single(),supabase.from('product_media').select('storage_path').eq('product_id',p.id).eq('kind','image').order('sort_order').limit(1).maybeSingle()]);const lang=req.query.lang==='en'?'en':'ar';res.json({product:{id:p.id,product_type:p.product_type,price_cents:p.price_cents,currency:p.currency,title:lang==='en'?p.title_en:p.title_ar,description:lang==='en'?p.description_en:p.description_ar,seller_id:p.seller_id,seller_name:throwIfError(sellerR).name,image_url:mediaR.data?`${supabaseUrl}/storage/v1/object/public/product-images/${mediaR.data.storage_path}`:null}});}catch(e){next(e);}});
 router.get('/seller/products',security.authenticate,security.allow('seller','owner','admin'),async(req,res,next)=>{try{const r=await supabase.from('products').select('id,title_ar,title_en,product_type,price_cents,currency,status,review_note,created_at,category_id').eq('seller_id',Number(req.auth.sub)).order('created_at',{ascending:false});const products=throwIfError(r);const cats=await supabase.from('categories').select('id,name_ar');const names=Object.fromEntries(throwIfError(cats).map(c=>[c.id,c.name_ar]));res.json({products:products.map(p=>({...p,category_name:names[p.category_id]||''}))});}catch(e){next(e);}});
 router.post('/seller/products',security.authenticate,security.allow('seller','owner','admin'),async(req,res,next)=>{try{const schema=z.object({categoryId:z.number().int().positive(),titleAr:z.string().trim().min(2).max(160),titleEn:z.string().trim().min(2).max(160),descriptionAr:z.string().trim().min(20).max(5000),descriptionEn:z.string().trim().min(20).max(5000),productType:z.enum(['digital','software','creative','service','course','physical']),priceCents:z.number().int().min(0),currency:z.string().length(3).transform(v=>v.toUpperCase()),submitForReview:z.boolean().default(false),publishNow:z.boolean().default(false)});const d=validate(schema,req.body,res);if(!d)return;const user=await userById(req.auth.sub);const requires=digitalTypes.includes(d.productType);const direct=['owner','admin'].includes(user.role)&&d.publishNow&&!requires;const status=direct?'published':d.submitForReview?'pending_review':'draft';const r=await supabase.from('products').insert({seller_id:user.id,category_id:d.categoryId,title_ar:d.titleAr,title_en:d.titleEn,description_ar:d.descriptionAr,description_en:d.descriptionEn,product_type:d.productType,price_cents:d.priceCents,currency:d.currency,status}).select().single();const p=throwIfError(r);await audit(user.id,'product.create','product',p.id,{status});res.status(201).json({id:p.id,status,fileRequiredBeforePublish:requires&&status==='draft'});}catch(e){next(e);}});
 router.post('/seller/products/:id/images',security.authenticate,security.allow('seller','owner','admin'),upload.single('image'),async(req,res,next)=>{try{if(!req.file)return res.status(400).json({error:'IMAGE_REQUIRED'});if(req.file.size>8*1024*1024)return res.status(413).json({error:'IMAGE_TOO_LARGE'});const user=await userById(req.auth.sub);const pr=await supabase.from('products').select('*').eq('id',Number(req.params.id)).maybeSingle();const p=throwIfError(pr);if(!canManage(user,p))return res.status(403).json({error:'FORBIDDEN'});const type=await fileTypeFromBuffer(req.file.buffer);if(!type||!['image/jpeg','image/png','image/webp'].includes(type.mime))return res.status(415).json({error:'UNSUPPORTED_IMAGE'});const buffer=await sharp(req.file.buffer).rotate().resize({width:1600,height:1600,fit:'inside',withoutEnlargement:true}).webp({quality:84}).toBuffer();const path=`${p.id}/${randomBytes(12).toString('hex')}.webp`;throwIfError(await supabase.storage.from('product-images').upload(path,buffer,{contentType:'image/webp',upsert:false}));const countR=await supabase.from('product_media').select('id',{count:'exact',head:true}).eq('product_id',p.id);const m=throwIfError(await supabase.from('product_media').insert({product_id:p.id,kind:'image',storage_path:path,mime_type:'image/webp',alt_ar:String(req.body.altAr||'').slice(0,200),alt_en:String(req.body.altEn||'').slice(0,200),sort_order:countR.count||0}).select().single());await audit(user.id,'product.image.add','product',p.id,{mediaId:m.id});res.status(201).json({media:{id:m.id,url:`${supabaseUrl}/storage/v1/object/public/product-images/${path}`}});}catch(e){next(e);}});
 router.post('/seller/products/:id/digital-files',security.authenticate,security.allow('seller','owner','admin'),upload.single('file'),async(req,res,next)=>{try{if(!req.file)return res.status(400).json({error:'FILE_REQUIRED'});const user=await userById(req.auth.sub);const p=throwIfError(await supabase.from('products').select('*').eq('id',Number(req.params.id)).maybeSingle());if(!canManage(user,p))return res.status(403).json({error:'FORBIDDEN'});if(!digitalTypes.includes(p.product_type))return res.status(400).json({error:'NOT_DIGITAL_PRODUCT'});const ext=(req.file.originalname.match(/\.[^.]+$/)?.[0]||'').toLowerCase();if(!['.xlsx','.xls','.csv','.zip','.pdf','.docx','.pptx','.txt'].includes(ext))return res.status(415).json({error:'UNSUPPORTED_FILE'});const path=`${p.id}/${randomBytes(18).toString('hex')}${ext}`;throwIfError(await supabase.storage.from('digital-private').upload(path,req.file.buffer,{contentType:req.file.mimetype||'application/octet-stream'}));const f=throwIfError(await supabase.from('digital_files').insert({product_id:p.id,storage_path:path,original_name:req.file.originalname.slice(0,255),mime_type:req.file.mimetype||'application/octet-stream',size_bytes:req.file.size,version:String(req.body.version||'1.0').slice(0,30)}).select().single());await audit(user.id,'product.digital_file.add','product',p.id,{fileId:f.id});res.status(201).json({file:{id:f.id,originalName:f.original_name,sizeBytes:f.size_bytes,version:f.version}});}catch(e){next(e);}});
 router.post('/seller/products/:id/publish',security.authenticate,security.allow('seller','owner','admin'),async(req,res,next)=>{try{const user=await userById(req.auth.sub);const p=throwIfError(await supabase.from('products').select('*').eq('id',Number(req.params.id)).maybeSingle());if(!canManage(user,p))return res.status(403).json({error:'FORBIDDEN'});if(digitalTypes.includes(p.product_type)){const files=await supabase.from('digital_files').select('id',{count:'exact',head:true}).eq('product_id',p.id).eq('is_active',true);if(!(files.count>0))return res.status(409).json({error:'DIGITAL_FILE_REQUIRED',message:'ارفع الملف قبل النشر.'});}const status=['owner','admin'].includes(user.role)?'published':'pending_review';throwIfError(await supabase.from('products').update({status,updated_at:new Date().toISOString()}).eq('id',p.id));await audit(user.id,'product.publish','product',p.id,{status});res.json({id:p.id,status});}catch(e){next(e);}});
 return router;
}
